<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    کوویدکاوی
</font>
</h1>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
در این تمرین می‌خواهیم داده‌های مربوط به وضعیت کووید-۱۹ در کشورهای مختلف جهان در یک روز از سال ۲۰۲۰ را کمی تحلیل کنیم و با پاسخ دادن به پرسش‌هایی از آن با کتابخانه‌ی <code>pandas</code> بیشتر کار کنیم.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مجموعه‌داده‌
</font>
</h2>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
ابتدا داده‌ها را از فایل <code>covid19-11-10-2020.csv</code> بخوانید و در متغیر <code>covid_data</code> ذخیره کنید.
</font>
</p>

In [39]:
import pandas as pd

In [41]:
covid_data = pd.read_csv('covid19-11-10-2020.csv')
covid_data.head()

,Unnamed: 0,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,0,NaN,NaN,NaN,Afghanistan,2020-11-11 05:25:30,33.93911,67.709953,42297,1574,34954.0,5769.0,Afghanistan,108.653487,3.721304
1,1,NaN,NaN,NaN,Albania,2020-11-11 05:25:30,41.15330,20.168300,25294,579,12353.0,12362.0,Albania,878.935298,2.289080
2,2,NaN,NaN,NaN,Algeria,2020-11-11 05:25:30,28.03390,1.659600,63446,2077,42626.0,18743.0,Algeria,144.685270,3.273650
3,3,NaN,NaN,NaN,Andorra,2020-11-11 05:25:30,42.50630,1.521800,5477,75,4405.0,997.0,Andorra,7088.591212,1.369363
4,4,NaN,NaN,NaN,Angola,2020-11-11 05:25:30,-11.20270,17.873900,12816,308,6036.0,6472.0,Angola,38.994388,2.403246

In [42]:
covid_data['Country_Region'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Brunei', 'Bulgaria', 'Burkina Faso', 'Burma', 'Burundi',
       'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada',
       'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia',
       'Comoros', 'Congo (Brazzaville)', 'Congo (Kinshasa)', 'Costa Rica',
       "Cote d'Ivoire", 'Croatia', 'Cuba', 'Cyprus', 'Czechia', 'Denmark',
       'Diamond Princess', 'Djibouti', 'Dominica', 'Dominican Republic',
       'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea',
       'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France',
       'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece',
       'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana',
       'Haiti', 'Holy See', 'Honduras', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya',
       'Korea, South', 'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia',
       'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein',
       'Lithuania', 'Luxembourg', 'MS Zaandam', 'Madagascar', 'Malawi',
       'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania',
       'Mauritius', 'Mexico', 'Moldova', 'Monaco', 'Mongolia',
       'Montenegro', 'Morocco', 'Mozambique', 'Namibia', 'Nepal',
       'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria',
       'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Qatar', 'Romania', 'Russia', 'Rwanda',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'Samoa', 'San Marino',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan',
       'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland',
       'Syria', 'Taiwan*', 'Tajikistan', 'Tanzania', 'Thailand',
       'Timor-Leste', 'Togo', 'Trinidad and Tobago', 'Tunisia', 'Turkey',
       'US', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela',
       'Vietnam', 'West Bank and Gaza', 'Yemen', 'Zambia', 'Zimbabwe',
       'Kiribati', 'Palau', 'Summer Olympics 2020', 'Malaysia', 'Tonga',
       'Winter Olympics 2022', 'Antarctica', 'Korea, North', 'Nauru',
       'Tuvalu'], dtype=object)

In [43]:
covid_data.columns

Index(['Unnamed: 0', 'FIPS', 'Admin2', 'Province_State', 'Country_Region',
       'Last_Update', 'Lat', 'Long_', 'Confirmed', 'Deaths', 'Recovered',
       'Active', 'Combined_Key', 'Incident_Rate', 'Case_Fatality_Ratio'],
      dtype='object')

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
    <font face="vazir" size=3>
        همان‌طور که احتمالاً دیده‌اید، این مجموعه‌داده دارای ۱۴ ویژگی/ستون است که به معرفی برخی از آن‌ها که مهم‌ترند می‌پردازیم. البته که شما باید تشخیص بدهید که در هر سوال کدام موارد به کار می‌آیند.
        <br>
       - ستون  <code>Country_Region</code>: مشخص است که نام کشور یا منطقه را مشخص می‌کند. دقت کنید که شاید لازم باشد بررسی کنید که آیا تعداد سطرها با تعداد کشورها برابر است و به بیان دیگر به ازای هر منطقه یا کشور فقط یک سطر دیتا وجود دارد یا خیر.
        <br>
        - ستون‌های <code>Long</code> و <code>Lat</code>: طول و عرض جفرافیایی کشور/منطقه را بیان می‌کند.
        <br>
        - ستون <code>Confirmed</code>: تعداد موارد تاییدشده‌ی ابتلا به ویروس
        <br>
        - ستون <code>Deaths</code>: تعداد موارد فوت‌شده
        <br>
        - ستون <code>Recovered</code>: تعداد موارد بهبودیافته
        <br>
        - ستون <code>Active</code>: تعداد موارد فعال (که از تفاضل مجموع فوتی‌ها و بهبودیافتگان از موارد تایید شده نیز به‌دست می‌آید.)
        <br>
        - ستون <code>Incident_Rate</code>: بیانگر تعداد موارد در هر ۱۰۰۰۰۰ نفر است.
</p>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<b style="color:red">نکته‌:</b>
در هر سوال که از شما خواسته‌شده پاسخ را در قالب فایلی با فرمت <code>csv</code> ذخیره کنید، لازم نیست نام ستون‌ها را ذخیره کنید (به بیان دیگر لازم نیست  <code>header</code> داشته باشند).
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت اول‌
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
     در ابتدا می‌خواهیم ببینیم ۱۰ کشور با بیشترین تعداد موارد  کدام‌اند. برای این کار می‌توانیم از
ستون  <code>Incident_Rate</code> استفاده کنیم. البته برای این‌که به‌نوعی مجموع تقریبی موارد را از این ستون محاسبه کنیم می‌توانیم از متد <code>apply</code>  استفاده کنیم و ستونی جدید به نام <code>Total_Cases</code> اضافه کنیم که از حاصل ضرب ۱۰۰۰۰۰ در مقادیر ستون <code>Incident_Rate</code> توسط تابع <code>apply</code> به‌دست می‌آیند.
<br>
پاسخ شما باید دارای ۱۰ ردیف و ۲ ستون باشد که نام کشور/منطقه و <code>Total_Cases</code> را شامل می‌شود و آن را در فایلی به نام <code>top10cases.csv</code> ذخیره کنید. 
</font>
</p>

In [44]:
covid_data['Total_Cases'] = covid_data['Incident_Rate'].apply(lambda x: round(x*100000,0))
dta= covid_data.groupby('Country_Region').sum().reset_index()
top10cases=dta[['Country_Region','Total_Cases']].sort_values('Total_Cases',ascending=False)
top10cases=top10cases.head(10)
top10cases.to_csv('top10cases.csv', header=False)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت دوم
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
در ادامه می‌خواهیم ببینیم چه کشورهایی بیشترین نرخ ریکاوری را داشته‌اند. بدین منظور قصد داریم شاخصی تعریف کنیم تحت عنوان <code>Recovery_Rate</code> که از حاصل تقسیم تعداد بهبودیافتگان به تعداد موارد تایید شده بدست می‌آید. البته در ابتدا قصد داریم کشورها/مناطقی که موارد تایید شده، فوت شده و بهبودیافته‌ی آن‌ها صفر گزارش شده است را درنظر نگیریم.
پس ردیف‌هایی که مقدار هر سه ستون <code>Confirmed</code>، <code>Deaths</code> و <code>Recovered</code> آن‌ها صفر است را از دیتافریم اصلی حذف کنید. سپس می‌خواهیم در بین کشورهایی که موارد تاییدشده به ابتلای آنها از میانه‌ی این شاخص بیشتر است ببینیم کدام‌شان نرخ ریکاوری بهتری دارد. بدین منظور در بین این کشورها، فهرست آنهایی که نرخ ریکاوری آنها از میانگین این نرخ برای همه کشورها بیشتر است را به صورت نزولی  
 در فایلی به نام <code>recovery_rate.csv</code> ذخیره کنید. پس فیلتر اولیه بر اساس میانه‌ی تعداد موارد تایید شده‌ی مبتلایان و فیلتر دوم بر اساس میانگین نرخ ریکاوری است.
<br>
توجه داشته باشید که فایل شما باید شامل دو ستون باشد که به ترتیب نام کشور/منطقه و نرخ ریکاوری باشد و ترتیب آن به صورت نزولی بر اساس نرخ ریکاوری.
</font>
</p>

In [62]:
dta = covid_data.groupby('Country_Region')[['Recovered','Confirmed','Deaths']].sum().reset_index()
dta = dta.drop(dta[(dta['Recovered']==0)&(dta['Confirmed']==0)&(dta['Deaths']==0)].index)
dta.dropna(how="any", inplace=True)
conf_median=dta['Confirmed'].median()
dta['Recovery_Rate']=dta['Recovered']/dta['Confirmed']
average_recovery_rate=dta['Recovery_Rate'].mean()
result = dta[(dta['Recovery_Rate']>average_recovery_rate) & (dta['Confirmed']>conf_median)][['Country_Region', 'Recovery_Rate']].sort_values('Recovery_Rate', ascending=False)
result.to_csv('recovery_rate.csv', header=False)
result

           Country_Region  Recovery_Rate
159             Singapore       0.998485
144                 Qatar       0.978242
13                Bahrain       0.971412
68                  Ghana       0.970407
188  United Arab Emirates       0.967559
154          Saudi Arabia       0.962516
85                 Israel       0.960519
191            Uzbekistan       0.958958
36                  Chile       0.954639
193             Venezuela       0.946713
131               Nigeria       0.937780
96                 Kuwait       0.930837
80                  India       0.927950
164          South Africa       0.922918
140                  Peru       0.921110
134                  Oman       0.919636
135              Pakistan       0.919241
54                  Egypt       0.916884
71              Guatemala       0.910915
94           Korea, South       0.908882
141           Philippines       0.905366
24                 Brazil       0.905303
88                  Japan       0.891697
37                  China       0.882730
53                Ecuador       0.881880
90             Kazakhstan       0.879445
55            El Salvador       0.873557
195    West Bank and Gaza       0.865420
83                   Iraq       0.860195
97             Kyrgyzstan       0.859323
183                Turkey       0.857625
7               Argentina       0.856964
38               Colombia       0.848973
137                Panama       0.847171
16                Belarus       0.846223
81              Indonesia       0.845601
117                Mexico       0.842441
52     Dominican Republic       0.829438
0             Afghanistan       0.826394
122               Morocco       0.817796
33                 Canada       0.809595
21                Bolivia       0.807485
14             Bangladesh       0.805949
9               Australia       0.805826
126                 Nepal       0.803850
44                Croatia       0.780918
118               Moldova       0.775505
82                   Iran       0.754590
28                  Burma       0.749688
66                Georgia       0.744540
146                Russia       0.744340
48                Denmark       0.743997
11             Azerbaijan       0.742061

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت سوم
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
اکنون می‌خواهیم اوضاع سایر کشورها را با کشور خودمان مقایسه‌ای کنیم! از این روی می‌خواهیم ببینیم کدام کشورها با وجود این‌که مبتلایان بیشتری از ما داشته‌اند، مرگ و میر کمتری ثبت کرده‌اند.
<br>
پاسخ را در فایلی به نام <code> vsiran.csv </code> ذخیره کنید. فایل پاسخ باید حاوی ۴ ستون باشد که نام کشور/منطقه، موارد تایید شده، موارد فوت‌شده و موارد بهبودیافته را به‌صورت نزولی بر اساس تعداد موارد تایید شده در بر داشته باشد.
</font>
</p>

In [75]:
dta=covid_data.groupby('Country_Region').sum().reset_index()
vs_death_iran=int(dta['Deaths'][dta['Country_Region']=='Iran'])
vs_conf_iran=int(dta['Confirmed'][dta['Country_Region']=='Iran'])
result=dta[(dta['Deaths']<vs_death_iran)&(dta['Confirmed']>vs_conf_iran)]
vsiran=result[['Country_Region','Confirmed','Deaths','Recovered']].sort_values('Confirmed',ascending=False)
vsiran.to_csv('vsiran.csv', header= False)
vsiran

C:\Users\novin.toos\AppData\Local\Temp\ipykernel_8780\1847881607.py:2: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  vs_death_iran=int(dta['Deaths'][dta['Country_Region']=='Iran'])
C:\Users\novin.toos\AppData\Local\Temp\ipykernel_8780\1847881607.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  vs_conf_iran=int(dta['Confirmed'][dta['Country_Region']=='Iran'])

    Country_Region  Confirmed  Deaths  Recovered
146         Russia    1802762   30899  1341868.0
7        Argentina    1262476   34183  1081897.0
38        Colombia    1155356   33128   980866.0
164   South Africa     740254   19951   683194.0

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت چهارم
</font>
</h2>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
در ادامه می‌خواهیم ادعای سخنگوی وزارت بهداشت کشوری را ارزیابی کنیم که ادعا می‌کند کشورش با توجه به آمار فوتی‌هایشان در این روز، جزو ۲۰ درصد برتر جهان است (هنوز در آن زمان عبارتی مثل «کشورهای برتر یک درصد جهان» کشف نشده بود :) ).
<br>
ما تعداد مرگ‌های گزارش‌شده را به تنهایی کافی نمی‌دانیم و فرض کنید برای راستی‌آزمایی این ادعا می‌خواهیم از شاخص ساده‌ای چون <b style="color:#0099cc">نسبت تعداد متوفیان به مبتلایان</b> استفاده کنیم. البته برای اینکه اینقدر هم دیگر ساده نباشد (!)، می‌خواهیم کشورهایی که مبتلایان تایید شده‌ی کمی در این روز داشته‌اند را در نظر نگیریم و برای این کار ۲۰ درصد کشورهایی که کمترین مبتلایان را داشته‌اند را نیز کنار می‌گذاریم و سپس شاخص مربوطه را برای کشورهای باقی‌مانده لحاظ می‌کنیم.
<br>
مقدار شاخص را در ستونی به نام <code>death_ratio</code> ذخیره کرده و
فهرست ۲۰ درصد برتر را به همراه مقدار شاخص ذکر شده در فایلی به نام 
    <code>20percent.csv</code> ذخیره کنید.

</font>
</p>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<b style="color:orange">توجه:</b>
آن دسته از ردیف‌هایی که مقدار ستون <code>Confirmed</code> آن‌ها برابر صفر است را در نظر نگرفته و حذف کنید.
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<b style="color:green">راهنمایی:</b>
دیتافریم حاصل شامل ۳۰ ردیف خواهد بود.
</font>
</p>

In [92]:
df = covid_data.groupby(['Country_Region']).sum().reset_index()
df.drop(df[df['Confirmed']==0].index,inplace=True)
df.dropna()
threshold = df['Confirmed'].quantile(0.2)
df = df[df['Confirmed'] > threshold]
df['death_ratio'] = df['Deaths'] / df['Confirmed']
df = df[['Country_Region','death_ratio']].sort_values('death_ratio', ascending=True)
top_20 = df.head(int(0.2 * len(df)))
top_20.to_csv("20percent.csv", header=False)
top_20

           Country_Region  death_ratio
159             Singapore     0.000482
144                 Qatar     0.001730
167             Sri Lanka     0.002786
111              Maldives     0.003408
23               Botswana     0.003446
188  United Arab Emirates     0.003588
13                Bahrain     0.003949
46                 Cyprus     0.004428
160              Slovakia     0.004624
79                Iceland     0.004693
126                 Nepal     0.005747
72                 Guinea     0.005928
43          Cote d'Ivoire     0.006044
96                 Kuwait     0.006155
64                  Gabon     0.006313
68                  Ghana     0.006491
123            Mozambique     0.007126
110              Malaysia     0.007134
175            Tajikistan     0.007296
147                Rwanda     0.007602
100               Lebanon     0.007729
66                Georgia     0.008185
106            Luxembourg     0.008351
105             Lithuania     0.008366
85                 Israel     0.008413
191            Uzbekistan     0.008518
193             Venezuela     0.008738
195    West Bank and Gaza     0.008970
186                Uganda     0.009045
16                Belarus     0.009381

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به راهنمایی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [93]:
import zlib
import zipfile

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

file_names = ["top10cases.csv", "recovery_rate.csv", "vsiran.csv", "20percent.csv", "covid19.ipynb"]
compress(file_names)

File Paths:
['top10cases.csv', 'recovery_rate.csv', 'vsiran.csv', '20percent.csv', 'covid19.ipynb']